# Ghost UI
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ghost-route
  namespace: ghost
spec:
  parentRefs:
  - name: nlb-envoy-gw
    namespace: gateway
    group: gateway.networking.k8s.io	
    kind: Gateway
  hostnames:
  - "blog.z3cyber.tech"
  rules:
  # - matches:
  #   - headers:
  #     - name: "x-forwarded-for"
  #       value: "109.78.25.77"
  - backendRefs:
      - name: ghost
        port: 2368
        group: ''	
        kind: Service
        weight: 1	
    matches:	
      - path:	
          type: PathPrefix	
          value: /