---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: monitoring
spec:
  refreshInterval: 60m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault-secretstore # Must match SecretStore on the cluster
  target:
    name: minio-credentials # Name for the secret on the cluster
    creationPolicy: Owner
  dataFrom:
    - extract: 
        conversionStrategy: Default	
        decodingStrategy: None
        key: local-minio-credentials # Name in the OCI Vault
        metadataPolicy: None

