server:
  enabled: true
  replicaCount: 1
  retentionPeriod: 3d
  retentionDiskSpaceUsage: 9GB
  vmServiceScrape:
    enabled: false
  persistentVolume:
    enabled: true
    storageClassName: "longhorn"
    size: 10Gi
      
vector:
  enabled: true

dashboards:
  enabled: true
  labels:
    grafana_dashboard: '1'
  namespace: monitoring