#values.yaml
k8sServiceHost: "192.168.0.200" # This IP should be the IP of the master node
k8sServicePort: "6443"
kubeProxyReplacement: true
namespace: "kube-system"
ipam:
  mode: kubernetes
  operator:
    clusterPoolIPv4PodCIDRList: "10.244.0.0/16"

# Announce IPs from services' `.status.loadbalancer.ingress` field (automatically assigned by LB-IPAM).
l2announcements:
  enabled: true

# Announce manually assigned IPs from services' `.spec.externalIPs` field
externalIPs:
  enabled: true

# Enable Gateway API
gatewayAPI:
  enabled: true
  externalTrafficPolicy: Local
  #xffNumTrustedHops: 1
  
# Enable envoy
envoy:
  enabled: true
  rollOutPods: true
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy:
      - NET_BIND_SERVICE
      - CAP_NET_ADMIN
      - CAP_BPF
      - NET_ADMIN
      - SYS_ADMIN

# Setup mutual authentication
authentication:
  enabled: false
  mutual:
    spire:
      enabled: false
      install:
        enabled: false

encryption:
  enabled: true
  type: wireguard


# Increase rate limit when doing L2 announcements
k8sClientRateLimit:
  qps: 50
  burst: 200
  
operator:
  replicas: 1  # Uncomment this if you only have one node
  rollOutPods: true
# Roll out cilium agent pods automatically when ConfigMap is updated.
rollOutCiliumPods: true

# Enable Hubble
hubble:
  enabled: true
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    rollOutPods: true