apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - l2annoucements.yaml
  - ipaddresspool.yaml
  # - gateway.yaml
  # - http-redirect.yaml

helmCharts:
- name: cilium
  repo: https://helm.cilium.io
  namespace: kube-system
  version: 1.19.0
  releaseName: cilium
  valuesFile: cilium-values.yaml
  additionalValuesFiles:
  - cilium-values-monitoring.yaml