apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - l2annoucements.yaml
  - ipaddresspool.yaml
  # - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.3.0/config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  # - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.3.0/config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  # - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.3.0/config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  # - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.3.0/config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  # - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.3.0/config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  # - gateway.yaml
  # - http-redirect.yaml

helmCharts:
- name: cilium
  repo: https://helm.cilium.io
  namespace: kube-system
  version: 1.19.0
  releaseName: cilium
  valuesFile: cilium-values.yaml
  additionalValuesFiles:
  - cilium-values-monitoring.yaml