apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - httproutes.yaml


helmCharts:
- name: longhorn
  namespace: longhorn-system
  repo: https://charts.longhorn.io 
  version: 82.3.0
  releaseName: longhorn
  valuesFile: longhorn-values.yaml