global:
  imageRegistry: "docker.io"
  timezone: "Europe/Dublin"
  # -- Node selector for nodes allowed to run user-deployed components such as Longhorn Manager, Longhorn UI, and Longhorn Driver Deployer.
  nodeSelector: {}


defaultSettings:
  defaultReplicaCount: "2"

persistence:
  defaultClassReplicaCount: 1

csi:
  attacherReplicaCount: "1"
  provisionerReplicaCount: "1"
  resizerReplicaCount: "1"
  snapshotterReplicaCount: "1"

preUpgradeChecker:
            jobEnabled: false
longhornUI:
  replicas: 1

metrics:
  serviceMonitor:
    enabled: false



