apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externaldns-credentials
  namespace: external-dns
spec:
  refreshInterval: 60m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault-secretstore
  target:
    name: external-dns-secret
    creationPolicy: Owner
  data:
    - secretKey: EXTERNAL_DNS_PIHOLE_PASSWORD
      remoteRef:
        key: externaldns-credentials
        conversionStrategy: Default	
        decodingStrategy: None
        metadataPolicy: None

