apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - workflows-route.yml
  - permissions/default-user.yml
  - permissions/workflows-admin.yml
  - permissions/workflows-user.yml
  - permissions/secret-reader.yml
  - workflows-secrets.yml
  - ns.yaml
  - eventbus.yml
  - workflows-db.yml

helmCharts:
- name: argo-workflows
  namespace: argo
  repo: https://argoproj.github.io/argo-helm
  version: 0.47.3
  releaseName: workflows
  valuesFile: workflows-values.yml
- name: argo-events
  namespace: argo
  repo: https://argoproj.github.io/argo-helm
  version: 2.4.20
  releaseName: events
  valuesFile: events-values.yml