---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflows-admin
  namespace: argo
  annotations:
    workflows.argoproj.io/rbac-rule: "'workflows-admin' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "100"
automountServiceAccountToken: true
secrets:
  - name: workflows-admin.service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: workflows-admin.service-account-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: workflows-admin
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflows-admin
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources:
      - "*"
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: workflows-admin-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workflows-admin 
subjects:
- kind: ServiceAccount
  name: workflows-admin
  namespace: argo
