apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: homepage
    namespace: homepage
    files:
      - config/bookmarks.yaml
      - config/kubernetes.yaml
      - config/services.yaml
      - config/widgets.yaml
      - config/custom.css
      - config/custom.js
      - config/docker.yaml
      - config/settings.yaml


resources:
  - ns.yaml
  - crb.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - httproute.yaml
  - secret.yaml
  - homepage-secrets.yaml
