apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cf-detect-ip-policy.yaml
  - cf-envoy-gateway.yaml
  - cf-http-redirect.yaml
  - cf-ratelimit-policy.yaml
  # - cf-gw-auth-policy.yaml
  - gatewayclass.yaml
  - gw-client-secret.yaml
  - nlb-envoy-gateway.yaml
  - nlb-http-redirects.yaml
  - nlb-ratelimit-policy.yaml
  - redis.yaml
  
helmCharts:
- name: gateway-helm
  namespace: envoy-gateway-system
  repo: oci://docker.io/envoyproxy
  version: v1.6.3
  releaseName: envoy-gateway
  valuesFile: values.yaml