apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: 1.18.1
    helm:
      releaseName: cert-manager
      valueFiles:
      - $values/kubernetes/homelab/applications/cert-manager/values.yaml
  - repoURL: 'https://github.com/zazathomas/Homelab'
    targetRevision: HEAD
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
#      - Validate=true
#      - PrunePropagationPolicy=foreground
#      - PruneLast=true