apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cloudflare-token.yaml
  - cloudflare-issuer.yaml
  - production-certificate.yaml

helmCharts:
- name: cert-manager
  namespace: cert-manager
  repo: https://charts.jetstack.io
  version: 1.19.3
  releaseName: cert-manager
  valuesFile: values.yaml