# Keycloak
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-route
  namespace: keycloak
spec:
  parentRefs:
  - name: nlb-envoy-gw # gateway name
    namespace: gateway
    group: gateway.networking.k8s.io	
    kind: Gateway
  hostnames:
  - "sso.z3cyber.tech"
  rules:
  - backendRefs:
    - name: keycloak-service
      port: 80
      group: ''	
      kind: Service
      weight: 1
    matches:	
      - path:	
          type: PathPrefix	
          value: /
