apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: keycloak-backup
  namespace: databases
spec:
  cluster:
    name: keycloak-db
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
        barmanObjectName: r2-store
        serverName: keycloak-db