apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: wg-easy-wg
  namespace: wg-easy
spec:
  parentRefs:
    - name: nlb-envoy-gw
      namespace: gateway
      sectionName: wg-easy
      group: gateway.networking.k8s.io	
      kind: Gateway
  rules:
    - backendRefs:
        - name: wg-easy-wg
          port: 51820
          group: ''	
          kind: Service
          weight: 1
      matches:	
        - path:	
            type: PathPrefix	
            value: /