# Wireguard UI
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wg-easy-ui
  namespace: wg-easy
spec:
  parentRefs:
  - name: cf-envoy-gw
    namespace: gateway
    group: gateway.networking.k8s.io	
    kind: Gateway
  hostnames:
  - "wg-cloud.z3cyber.tech"
  rules:
  - backendRefs:
      - name: wg-easy-http
        port: 51821
        group: ''	
        kind: Service
        weight: 1
    matches:	
      - path:	
          type: PathPrefix	
          value: /