apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-secret-reader
  namespace: argo
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["workflows-secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-secret-reader-binding
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: workflows-admin
    namespace: argo
  - kind: ServiceAccount
    name: workflows-user
    namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-secret-reader
