---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workflows-user
  namespace: learning
  annotations:
    workflows.argoproj.io/rbac-rule: "'workflows-user' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "2"
automountServiceAccountToken: true
secrets:
  - name: workflows-user.service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: workflows-user.service-account-token
  namespace: learning
  annotations:
    kubernetes.io/service-account.name: workflows-user
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflows-user
  namespace: learning
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources:
      - eventsources
      - sensors
      - workflows
      - workflowtemplates
      - cronworkflows
      - workfloweventbindings
      - workflowtaskresults
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["argoproj.io"]
    resources:
      - clusterworkflowtemplates
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflows-user-rb
  namespace: learning
subjects:
- kind: ServiceAccount
  name: workflows-user
  namespace: learning
roleRef:
  kind: Role
  name: workflows-user
  apiGroup: rbac.authorization.k8s.io



