apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - podmonitor.yaml
  - namespaces.yaml
  - r2-secrets.yaml
  - https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.11.0/manifest.yaml
  - objectstore.yaml



helmCharts:
- name: cloudnative-pg
  namespace: cnpg-system
  repo: https://cloudnative-pg.github.io/charts
  version: 0.27.1
  releaseName: cnpg