apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storageClass.yaml
  - minio-service.yaml

helmCharts:
- name: csi-driver-nfs
  namespace: kube-system
  repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  version: 4.13.0
  releaseName: csi-driver-nfs