---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: workflows-secrets
  namespace: argo
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: oci-vault-secretstore # Must match SecretStore on the cluster
  target:
    name: workflows-secrets # Name for the secret on the cluster
    creationPolicy: Owner
  dataFrom:
    - extract: 
        conversionStrategy: Default	
        decodingStrategy: None
        key:  workflows-secrets # Key in the OCI Vault
        metadataPolicy: None