---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd-route-cf
  namespace: argocd
spec:
  parentRefs:
  - name: cf-envoy-gw
    namespace: gateway
    group: gateway.networking.k8s.io	
    kind: Gateway
  hostnames:
  - "argocd-home.z3cyber.tech"
  rules:
   - backendRefs:
      - name: argocd-server
        port: 80
        group: ''	
        kind: Service
        weight: 1	
     matches:	
        - path:	
            type: PathPrefix	
            value: /