apiVersion: v1
kind: ServiceAccount
metadata:
  name: wf-runner
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wf-runner
  namespace: argo
rules:
  - apiGroups: [""]
    resources: ["pods","pods/log"]
    verbs: ["get","list","watch"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflowtaskresults"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wf-runner
  namespace: argo
subjects:
  - kind: ServiceAccount
    name: wf-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wf-runner
