apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret-cf-token.yaml
  - Issuers/letsencrypt-staging.yaml
  - Issuers/letsencrypt-production.yaml
  - certificates/staging/staging-cert.yaml
  - certificates/production/z3cyber-tech-cert.yaml

helmCharts:
- name: cert-manager
  namespace: cert-manager
  repo: https://charts.jetstack.io
  version: 1.19.3
  releaseName: cert-manager
  valuesFile: values.yaml