apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi
  namespace: argocd
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://strimzi.io/charts/'
    chart: strimzi-kafka-operator
    targetRevision: 0.46.0
    helm:
      releaseName: strimzi
      valueFiles:
      - $values/kubernetes/homelab/applications/strimzi/values.yaml
  - repoURL: 'https://github.com/zazathomas/Homelab'
    targetRevision: HEAD
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: strimzi-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true