apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: tailing-sidecar-operator
  namespace: tailing-sidecar
  repo: https://sumologic.github.io/tailing-sidecar
  version: 0.111.0 
  releaseName: tailing-sidecar
  valuesFile: values.yaml